### ISSUE TITLE
Calvin: there is little to no use of styled-components throughout module

### ISSUE THREAD

**Issue by eric-do** [Weyland-Software-Group/fec#56]
I think the only component I see Styled Components in is your styleSelector component. I gave you warning ahead that you do not want to write everything out with regular HTML tags first then refactor later - you should have written code with Styled Components from the beginning, and now a refactor will be very time intensive.

**Comment by chu017** [comment]
Hi, Eric. Do we must use the styled components for this project? I thought that is an option. I don't know that we don't allow to use the regular CSS setting for this project.

**Comment by eric-do** [comment]
Calvin, it was an explicit change request made in announcements the day
after FEC kickoff:
https://hrsf134.slack.com/archives/C01Q1Q9L6TU/p1618352678131400

This is link to the doc:
https://docs.google.com/document/d/1VO0Nn9HKzQfv9cmpdvdgmMAYspxtisL6ZqtvlJb1mlI/edit?usp=sharing
