### ISSUE TITLE
Calvin: prefer class declarations over class expressions

### ISSUE THREAD

**Issue by eric-do** [Weyland-Software-Group/fec#58]
https://github.com/Weyland-Software-Group/fec/blob/3989f7093f1e093fa6251a47dfc4d9b2b1830300/client/src/components/Overview/imageGallery/imageGallery.jsx#L15

Unless you have a specific reason to use [class expressions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/class), prefer [class declarations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#class_declarations) instead.

**Comment by chu017** [comment]
I fixed it. But what is the benefit to use the class expressions over the class declarations?

**Comment by dootMaster** [comment]
Eric linked you to the MDN pages in his comment above:

> There are several differences between class expressions and class statements, however:
>
>Class expressions may omit the class name ("binding identifier"), which is not possible with class statements.
>Class expressions allow you to redefine (re-declare) classes without throwing a SyntaxError. This is not the case with class statements.

There is more information if you go to those links.
