### ISSUE TITLE
Praneeth: watch out for clashing method names

### ISSUE THREAD

**Issue by eric-do** [Weyland-Software-Group/fec#61]
https://github.com/Weyland-Software-Group/fec/blob/3989f7093f1e093fa6251a47dfc4d9b2b1830300/client/src/components/QA/SubComponents/AnswerRenderer.jsx#L39

Even if this code works by invoking the imported method instead of invoking the current method recursively, it would be confusing to anyone who reads your code to know if they're looking at a bug or not.

**Comment by pgoggles** [comment]
Wow thank you, I'm not sure how I missed such a big glaring error, that is definitely bad naming practices, I'll look through the rest and see if I can fix up naming. Thank you for the suggestion!
