### ISSUE TITLE
Leslie:  be more concise around boolean logic

### ISSUE THREAD

**Issue by eric-do** [Weyland-Software-Group/fec#64]
https://github.com/Weyland-Software-Group/fec/blob/3989f7093f1e093fa6251a47dfc4d9b2b1830300/client/src/components/Related/subcomponents/card/CardStateful.jsx#L32

A couple things here:
1. You don't have to use === when comparing to a boolean. You can just say `if (isVisible) {...}`.
2. You can further condense your code using !

```javascript
toggleModal() {
    const { isVisible } = this.state;
    this.setState({ isVisible: !isVisible });
}
```

**Comment by dootMaster** [comment]
I've fixed this, and used #2 to refactor the toggle function. I will continue to look for other areas in my code where I can make these changes.
