### ISSUE TITLE
Leslie:  use array methods and functional programming where you can

### ISSUE THREAD

**Issue by eric-do** [Weyland-Software-Group/fec#65]
https://github.com/Weyland-Software-Group/fec/blob/3989f7093f1e093fa6251a47dfc4d9b2b1830300/client/src/components/Related/subcomponents/card/CardStateful.jsx#L53

It's probably not necessary for you to use an imperative loop here. For the search and compare, you can probably also  use something like Array.prototype.findIndex

**Comment by dootMaster** [comment]
I see that what I had written uses nested loops. Operations results in O(n^2). No bueno.

This is my new code. I've also changed a few variable names to reflect better practices. Thanks for the tip, Eric. 

`    const tableData = [];

    Object.keys(overviewFeatures).forEach((key) => {
      tableData.push({
        featureToCompare: key,
        overviewValue: overviewFeatures[key],
        cardValue: configuredCardFeatures[key] || '',
      });
    });
    Object.keys(configuredCardFeatures).forEach((key) => {
      if (!overviewFeatures[key]) {
        tableData.push({
          featureToCompare: key,
          overviewValue: '',
          cardValue: configuredCardFeatures[key],
        });
      }
    });

    this.setState({
      comparisonData: tableData,
    });`
